  language: python
  
  python:
    - "3.6"
  
  script:
    - python -m unittest discover -p "*tests.py"
    - coverage run -m unittest discover -p "*tests.py"
    - coverage report -m 

  after_success:
    codecov
